# Reference: https://github.com/ros-tooling/action-ros-ci-template/blob/master/.github/workflows/lint.yml

name: Lint ROS 2 package
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Note that we pass each job a different name to distinguish each linter job
  ament_lint_cpp:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [clang_format, clang_tidy, xmllint, copyright, lint_cmake]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ros-tooling/setup-ros@0.6.1
      - uses: ros-tooling/action-ros-lint@0.1.3
        with:
          linter: ${{ matrix.linter }}
          package-name: cpp_template_pkg
