# Reference: https://github.com/ros-tooling/action-ros-ci-template/blob/master/.github/workflows/lint.yml

name: Lint ROS 2 package
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Note that we pass each job a different name to distinguish each linter job
  ros_ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: humble
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: my_package
        target-ros2-distro: humble
