name: Lint ROS 2 package
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ros_ci:
    runs-on: ubuntu-22.04
    steps:
    - uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: humble
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        target-ros2-distro: humble
